/**
 * API types for frontend specs.
 * Source of truth verified against GET /openapi.json from backend /docs.
 */

/** Allowed operation type in API filters and payloads. */
export type OperationType = "income" | "outcome";

/** Allowed business segmentation type in API filters and payloads. */
export type BusinessType = "B2B" | "B2C";

/** Allowed category values returned by the metrics API. */
export type Category =
  | "suppliers"
  | "sales"
  | "operational"
  | "administrative"
  | "others";

/**
 * Record returned by GET /api/metrics.
 */
export interface FinancialMovement {
  /** Date of the movement in YYYY-MM-DD format (OpenAPI: string/date). */
  create_date: string;
  /** Raw amount of the movement. */
  amount: number;
  /** Movement type. */
  operation_type: OperationType;
  /** Category bucket. */
  category: Category;
  /** Business segment. */
  business_type: BusinessType;
}

/**
 * Response from GET /api/metrics.
 */
export type MetricsResponse = FinancialMovement[];

/**
 * Response from GET /api/metrics/facets.
 */
export interface MetricsFacetsResponse {
  /** Distinct operation types available in current dataset. */
  operation_types: OperationType[];
  /** Distinct business types available in current dataset. */
  business_types: BusinessType[];
  /** Distinct categories available in current dataset. */
  categories: Category[];
  /** Minimum date available in dataset (YYYY-MM-DD). */
  min_date: string;
  /** Maximum date available in dataset (YYYY-MM-DD). */
  max_date: string;
}

/**
 * Allowed group granularity for alerts endpoint.
 */
export type GroupBy = "day" | "week" | "month";

/**
 * One row returned by GET /api/metrics/alerts.
 */
export interface MetricsAlertEntry {
  /**
   * Aggregated period label generated by backend.
   * Examples by group_by: YYYY-MM-DD, YYYY-Www, YYYY-MM.
   */
  period: string;
  /** Outcome total of the period (same unit as movements amount). */
  outcome_total: number;
  /**
   * Baseline average used by backend for comparison.
   * Note: API exposes baseline_average; window size is not encoded in payload.
   */
  baseline_average: number;
  /**
   * Ratio increase vs baseline (not percentage).
   * Example: 0.25 means +25%.
   */
  increase_ratio: number;
}

/**
 * Response from GET /api/metrics/alerts.
 */
export type MetricsAlertsResponse = MetricsAlertEntry[];

/**
 * One row returned by GET /api/metrics/categories/top.
 */
export interface TopCategoryEntry {
  /** Category name. */
  category: Category;
  /** Operation type used in aggregation. */
  operation_type: OperationType;
  /** Total amount for this category within current filter scope. */
  total_amount: number;
}

/**
 * Response from GET /api/metrics/categories/top.
 */
export type TopCategoriesResponse = TopCategoryEntry[];
